/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from 'react';

export const Index: Record<string, any> = {
  'wallet-adapter': {
    name: 'wallet-adapter',
    description:
      'A Solana wallet connection button with a dialog wallet picker and connected-state dropdown.',
    type: 'registry:component',
    files: [
      {
        path: 'src/registry/components/wallet-adapter/wallet-adapter.tsx',
        type: 'registry:component',
        target: '@components/wallet-adapter.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/components/wallet-adapter/wallet-adapter.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ['web3', 'authentication'],
    meta: undefined,
  },
  'key-screen': {
    name: 'key-screen',
    description:
      'A floating overlay that captures and displays keyboard shortcuts and keypresses in real time — ideal for demos, screencasts, and presentations.',
    type: 'registry:component',
    files: [
      {
        path: 'src/registry/components/key-screen/key-screen.tsx',
        type: 'registry:component',
        target: '@components/key-screen.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/components/key-screen/key-screen.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ['utility', 'overlay', 'keyboard', 'interaction'],
    meta: undefined,
  },
  'masonry-feed': {
    name: 'masonry-feed',
    description:
      'A Pinterest-style image feed that places images left to right into the shortest column using manual height calculation — no CSS grid required.',
    type: 'registry:component',
    files: [
      {
        path: 'src/registry/components/masonry-feed/masonry-feed.tsx',
        type: 'registry:component',
        target: '@components/masonry-feed.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/components/masonry-feed/masonry-feed.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ['media', 'gallery', 'interactive'],
    meta: undefined,
  },
  'wallet-adapter-demo': {
    name: 'wallet-adapter-demo',
    description: '',
    type: 'registry:example',
    files: [
      {
        path: 'src/registry/examples/wallet-adapter-demo.tsx',
        type: 'registry:example',
        target: '@components/wallet-adapter-demo.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/examples/wallet-adapter-demo.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'key-screen-demo': {
    name: 'key-screen-demo',
    description: '',
    type: 'registry:example',
    files: [
      {
        path: 'src/registry/examples/key-screen-demo.tsx',
        type: 'registry:example',
        target: '@components/key-screen-demo.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/examples/key-screen-demo.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  'masonry-feed-demo': {
    name: 'masonry-feed-demo',
    description: '',
    type: 'registry:component',
    files: [
      {
        path: 'src/registry/examples/masonry-feed-demo.tsx',
        type: 'registry:example',
        target: '@components/masonry-feed-demo.tsx',
      },
    ],
    component: React.lazy(async () => {
      const mod = await import('@/registry/examples/masonry-feed-demo.tsx');
      const exportName =
        Object.keys(mod).find(
          (key) => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
};
