name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8

      - name: Install dependencies
        run: bun install --forzen-lockfile

      - name: Build application
        run: bun run build

      - name: Verify
        run: bun run verify

      - name: Type check
        run: bun run type-check

      - name: Lint
        run: bun run lint

      - name: Check formatting
        run: bun run format:check

      - name: Validate content
        run: bun run content:validate

      - name: Build component registry
        run: bun run registry:build

      - name: Validate component registry
        run: bun run registry:validate
